// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqBQsbbduO7WR_vs09ddOQRfwenS9uk6Q',
    appId: '1:485345571966:web:f85e69119b169c341f942f',
    messagingSenderId: '485345571966',
    projectId: 'office-attendence-47df9',
    authDomain: 'office-attendence-47df9.firebaseapp.com',
    storageBucket: 'office-attendence-47df9.firebasestorage.app',
    measurementId: 'G-YEYPCFW8G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0eFUuiwLQ0K_RbEOyPXtmyibHOfJltE',
    appId: '1:485345571966:android:4297ba61ce31f9b11f942f',
    messagingSenderId: '485345571966',
    projectId: 'office-attendence-47df9',
    storageBucket: 'office-attendence-47df9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcER4fzewjycPDLstjFkyiti9nJANXXAo',
    appId: '1:485345571966:ios:2d588ce6eb316a421f942f',
    messagingSenderId: '485345571966',
    projectId: 'office-attendence-47df9',
    storageBucket: 'office-attendence-47df9.firebasestorage.app',
    iosBundleId: 'com.example.officeAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcER4fzewjycPDLstjFkyiti9nJANXXAo',
    appId: '1:485345571966:ios:2d588ce6eb316a421f942f',
    messagingSenderId: '485345571966',
    projectId: 'office-attendence-47df9',
    storageBucket: 'office-attendence-47df9.firebasestorage.app',
    iosBundleId: 'com.example.officeAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqBQsbbduO7WR_vs09ddOQRfwenS9uk6Q',
    appId: '1:485345571966:web:d4e77a3b8e251a411f942f',
    messagingSenderId: '485345571966',
    projectId: 'office-attendence-47df9',
    authDomain: 'office-attendence-47df9.firebaseapp.com',
    storageBucket: 'office-attendence-47df9.firebasestorage.app',
    measurementId: 'G-T08FJBDVQ2',
  );
}
